root = "."
tmp = ""

[build]
bin = "/usr/bin/true"
cmd = "make build/css"
include_dir = ["styles"]
include_ext = ["css"]
log = "air.css.log"

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = true
time = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
